language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy
      deploy:
        provider: npm
        email: "marksz@teamsz.xyz"
        api_key: "${NPM_TOKEN}"
        skip_cleanup: true
        on:
          branch: master
branches:
  only:
    - master
